accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

config/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static

from webfacetg.views import home, DeactivateUserAPIView
from webfacetg.api_views import LotteryUpdateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    path('telegram_users/', include("webfacetg.urls", namespace="tg_users")),
    path('posts/', include("post.urls", namespace="posts")),

    path('api/', include("post.api_urls", namespace="posts_api")),

    path('api/users/<int:user_id>/deactivate/', DeactivateUserAPIView.as_view(),
         name='deactivate-user'),
    path("api/v1/lotteries/<int:lottery_id>/", LotteryUpdateView.as_view(),
         name="get_lottery_by_id"),
]


# Кастомная функция для обработки 404
def custom_404(request, exception):
    return render(request, '404.html', status=404)


# Назначаем обработчик
handler404 = custom_404

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path('weekly-posts/', views.weekly_posts_editor, name='weekly_posts_editor'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator
from django.db import models

from .managers.managers import CustomUserManager
from .validators.validators_user_model import (
    name_validators,
    email_validator,
    password_validators,
    validate_image_size
)
from .utils import avatar_upload_to


class User(AbstractUser):
    first_name = models.CharField(
        verbose_name="Имя",
        max_length=30,
        validators=name_validators,
    )
    last_name = models.CharField(
        verbose_name="Фамилия",
        max_length=30,
        blank=True,
        validators=name_validators,
    )
    email = models.EmailField(
        verbose_name="Email",
        unique=True,
        max_length=100,
        validators=[email_validator],
        error_messages={
            'invalid': 'Введите правильный адрес электронной почты.'
        }
    )
    password = models.CharField(
        verbose_name="Пароль",
        max_length=128,
        validators=password_validators,
    )
    avatar = models.ImageField(
        verbose_name="Аватар",
        upload_to=avatar_upload_to,
        blank=True,
        validators=[
            FileExtensionValidator(allowed_extensions=['jpg', 'png']),
            validate_image_size,  # Валидация размера файла и изображения
        ]
    )
    is_admin = models.BooleanField(
        verbose_name="Администратор",
        default=False
    )
    username = None

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name']

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return f'{self.first_name} {self.last_name} <{self.email}>'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            'avatar',
            "is_active",
            'is_staff',
            'is_superuser',
            "is_admin"
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'placeholder': 'Ваше имя'})
        self.fields['last_name'].widget.attrs.update({'placeholder': 'Ваша фамилия'})
        self.fields['email'].widget.attrs.update({'placeholder': 'Ваш Email'})
        self.fields['is_active'].label = 'Активный пользователь поле is_active (Django field)'
        self.fields['is_staff'].label = 'Администратор поле is_staff (Django field)'
        self.fields['is_superuser'].label = 'Суперпользователь поле is_superuser (Django field)'
        self.fields['is_admin'].label = 'Наше кастомное поле для is_admin'


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
        label="Email"
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'}),
        label="Пароль"
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import UserLoginForm


def user_login(request):
    if request.method == "POST":
        user_login_form = UserLoginForm(request.POST)
        if user_login_form.is_valid():
            email = user_login_form.cleaned_data['email']
            password = user_login_form.cleaned_data['password']

            # Аутентификация по email и паролю
            user = authenticate(request, email=email, password=password)

            if user is not None:
                if not user.is_admin:  # Проверка, что пользователь не администратор
                    messages.error(request, "Вы не являетесь администратором")
                    return redirect('home')  # Замените 'home' на нужный URL

                if user.is_active and user.is_admin:  # Проверка на активность и админ-статус
                    login(request, user)
                    messages.success(request, "Вы успешно вошли в систему.")
                    return redirect('home')  # Замените 'home' на нужный URL
            else:
                messages.error(request, "Неправильный email или пароль.")
                return redirect('home')  # Редирект для некорректного пользователя
    else:
        user_login_form = UserLoginForm()

    return render(request, 'accounts/login.html', {'form': user_login_form})


def logout_view(request):
    logout(request)  # Завершаем сессию пользователя
    return redirect(to="accounts:login")  # Перенаправляем на страницу логина

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Home page</title>
{% endblock title %}

{% block css %}
{% endblock %}

{% block content %}

    <div class="container d-flex justify-content-center align-items-center min-vh-100">
        <div class="w-100" style="max-width: 600px;">

            {% if request.user.is_authenticated %}
                <h4 class="text-center mt-2 mb-4">Вы залогинены. Можете пользоваться контентом</h4>
                <div class="d-flex justify-content-center">
                    <a href="{% url 'accounts:logout' %}" class="btn btn-danger">Выйти из
                        системы</a>

                </div>
            {% else %}
                <h4 class="text-center mt-2 mb-4">Вход в систему (только администратор)</h4>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="d-flex justify-content-center align-items-start"
                         style="min-height: 50px; color: red">
                        {% if messages %}
                            <ul class="list-unstyled mb-0">
                                {% for message in messages %}
                                    <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>

                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-success">Войти</button>
                    </div>
                </form>
            {% endif %}

            <!-- Уведомление -->
            {% if messages %}
                <div id="notification-container"
                     class="toast-container position-fixed bottom-0 end-0 p-3">
                    {% for message in messages %}
                        <div class="toast align-items-center text-bg-success border-0 show"
                             role="alert" aria-live="assertive" aria-atomic="true"
                             data-bs-autohide="true" data-bs-delay="7000">
                            <div class="d-flex">
                                <div class="toast-body">
                                    {{ message }}
                                </div>
                                <button type="button" class="btn-close btn-close-white me-2 m-auto"
                                        data-bs-dismiss="toast" aria-label="Close"></button>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}


        </div>
    </div>

{% endblock content %}