config/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static

from webfacetg.views import home, DeactivateUserAPIView
from webfacetg.api_views import LotteryUpdateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    path('telegram_users/', include("webfacetg.urls", namespace="tg_users")),
    path('posts/', include("post.urls", namespace="posts")),

    path('api/', include("post.api_urls", namespace="posts_api")),

    path('api/users/<int:user_id>/deactivate/', DeactivateUserAPIView.as_view(),
         name='deactivate-user'),
    path("api/v1/lotteries/<int:lottery_id>/", LotteryUpdateView.as_view(),
         name="get_lottery_by_id"),
]


# Кастомная функция для обработки 404
def custom_404(request, exception):
    return render(request, '404.html', status=404)


# Назначаем обработчик
handler404 = custom_404

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path('weekly-posts/', views.weekly_posts_editor, name='weekly_posts_editor'),
]

webfacetg/urls.py
from django.urls import path
from . import views

app_name = "webfacetg"

urlpatterns = [
    path('users/', views.get_all_tg_users, name="get_all_tg_users"),
    path('users/edit/<int:pk>/', views.edit_tg_user, name="edit_users"),
    path('all_lotteries/', views.get_list_lotteries, name="all_lotteries"),
    path('create_lottery/', views.create_lottery, name="create_lottery"),
    path('users/lottery/<int:pk>/participants/',
         views.get_list_participants_lottery,
         name="lottery_users"),
    path('users/lottery/<int:pk>/participants/download/',
         views.download_participants_lottery,
         name='download_participants_lottery'),
    path('users/lottery/all_users/download/',
         views.download_all_tg_users,
         name='download_all_tg_users'),
]

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    {% block title %}
        <title></title>
    {% endblock title %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"#}
{#          rel="stylesheet">#}

    <!-- Main CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>

    {% block css %}
    {% endblock css %}
</head>
<body>

<header>
    <nav class="header-nav">
        <ul class="menu">
            <li><a href="{% url 'home' %}">Главная</a></li>
            <li><a href="{% url 'webfacetg:get_all_tg_users' %}">Список пользователей</a></li>
            <li ><a href="{% url 'webfacetg:all_lotteries' %}">Список лотерей</a></li>
            {% if request.user.is_authenticated %}
            <li ><a href="{% url 'webfacetg:create_lottery' %}">Создать лотерею</a></li>
            <li ><a href="{% url 'posts:weekly_posts_editor' %}">Редактировать посты</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

<main>
    {% block content %}
    {% endblock %}
</main>

{#<footer>#}
{#    <div>footer</div>#}
{#</footer>#}

<!-- Кнопка "Вверх" -->
<button id="scrollToTopBtn" class="btn btn-secondary" title="Наверх">
    ↑
</button>


<!-- Bootstrap JS -->
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>#}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const scrollToTopBtn = document.getElementById("scrollToTopBtn");

        // Показать/скрыть кнопку при прокрутке
        window.addEventListener("scroll", () => {
            if (window.scrollY > 300) { // Показать кнопку, если прокрутка > 300px
                scrollToTopBtn.style.display = "flex";
            } else {
                scrollToTopBtn.style.display = "none";
            }
        });

        // Прокрутка страницы вверх при нажатии
        scrollToTopBtn.addEventListener("click", () => {
            window.scrollTo({
                top: 0,
                behavior: "smooth" // Плавная прокрутка
            });
        });
    });
</script>


</body>
</html>